[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "openai>=2.53.0",
    "psycopg2>=2.9.12",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.fastapi]
entrypoint = "app.main:app"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
